# Generated by Django 3.0.8 on 2020-12-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0005_payments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='transaction_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
