# Generated by Django 3.0.8 on 2020-12-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0007_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_status',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
